name: s_rocks_music
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cloud_firestore: ^4.15.5
  firebase_core: ^2.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/  # optional if you need to declare fonts folder for other use
    - assets/user.png
    - assets/circular.png
    - assets/keyboard.png
    - assets/image.png

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf